# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U tox
- pip install coveralls
# command to run tests, e.g. python setup.py test
script:
- tox -e ${TOXENV}
- coverage run --source=mcmc/mcmc.py setup.py test
- coverage report -m

after_success: coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mchakra2
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: mchakra2/mcmc
    condition: $TOXENV == py27
